// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class Foreign_keys_NOT_NULL_fix_part3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Foreign_keys_NOT_NULL_fix_part3));
        
        string IMigrationMetadata.Id
        {
            get { return "201312081900159_Foreign_keys_NOT_NULL_fix_part3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
