// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class Person_and_Order_configuration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Person_and_Order_configuration));
        
        string IMigrationMetadata.Id
        {
            get { return "201312071522549_Person_and_Order_configuration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
