// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class OrderItem_Remarks_and_Accepted_columns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrderItem_Remarks_and_Accepted_columns));
        
        string IMigrationMetadata.Id
        {
            get { return "201312081424479_OrderItem_Remarks_and_Accepted_columns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
