// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class Order_OrderItems_association : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Order_OrderItems_association));
        
        string IMigrationMetadata.Id
        {
            get { return "201312081445558_Order_OrderItems_association"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
